FROM golang:1.26-alpine AS builder

WORKDIR /app 

COPY go.mod go.sum ./
RUN go mod download

COPY . . 

RUN go build -o api ./cmd/api 
RUN go build -o worker ./cmd/worker 

FROM alpine:3.20

WORKDIR /app 

RUN apk add --no-cache ca-certificates curl \
 && ARCH=$(uname -m) \
 && if [ "$ARCH" = "x86_64" ]; then \
      URL="https://github.com/golang-migrate/migrate/releases/download/v4.17.0/migrate.linux-amd64.tar.gz"; \
    else \
      URL="https://github.com/golang-migrate/migrate/releases/download/v4.17.0/migrate.linux-arm64.tar.gz"; \
    fi \
 && curl -L $URL | tar -xz \
 && mv migrate /usr/local/bin/migrate

COPY --from=builder /app/api .
COPY --from=builder /app/worker .
COPY migrations /migrations

RUN apk add --no-cache ca-certificates 

CMD ["./api"]