apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: us-west1-docker.pkg.dev/cloud-native-docs-495722/cloud-native-docs/api:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"
          requests:
            memory: "512Mi"
            cpu: "500m"
        env:
          - name: JAEGER_COLLECTOR
            value: jaeger-svc:4318
          - name: POSTGRES_HOST
            value: "127.0.0.1"
          - name: POSTGRES_PORT
            value: "5432"
          - name: NATS_URL
            value: nats://nats-svc:4222
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                key: POSTGRES_USER
                name: postgres-secret
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                key: POSTGRES_PASSWORD
                name: postgres-secret
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                key: POSTGRES_DB
                name: postgres-secret
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                key: JWT_SECRET
                name: api-secret
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0
        args:
          - "--structured-logs"
          - "--port=5432"
          - "cloud-native-docs-495722:us-west1:cloud-native-docs-db"
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /secrets/sa-key.json
        securityContext:
          runAsNonRoot: true
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
        volumeMounts:
          - name: sa-key
            mountPath: /secrets
            readOnly: true
      volumes:
        - name: sa-key
          secret:
            secretName: cloudsql-sa-key
---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
  - port: 80
    targetPort: 8080
