apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-scaledobject
spec:
  scaleTargetRef:
    name: worker-deployment
  minReplicaCount: 1
  maxReplicaCount: 5
  cooldownPeriod: 30
  triggers:
    - type: nats-jetstream
      metadata:
        natsServerMonitoringEndpoint: "nats-svc.default.svc.cluster.local:8222"
        account: "$G"
        stream: "DOCUMENT_EVENTS"
        consumer: "WORKER_CONSUMER"
        lagThreshold: "10"