apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: mehrnazm/docs-api:v1.0.0
          imagePullPolicy: Always
          command:
            - sh
            - -c
            - |
              migrate \
              -path /migrations \
              -database "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${DB_HOST}:${DB_PORT}/${POSTGRES_DB}?sslmode=disable" \
              up
          envFrom:
            - secretRef:
                name: postgres-secret
          env:
            - name: DB_HOST
              value: postgres-svc
            - name: DB_PORT
              value: "5432"